# Generated by Django 4.2.1 on 2024-04-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(default='product', max_length=300)),
                ('productPrice', models.IntegerField(default=0)),
                ('productImage', models.CharField(max_length=600)),
                ('rating', models.IntegerField(default=5)),
            ],
        ),
    ]
