# Generated by Django 4.2.1 on 2024-04-16 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='gender',
            field=models.CharField(default='FEMALE', max_length=7),
        ),
    ]
